######################################################################
# Automatically generated by qmake (2.01a) ?? 30. ??? 14:32:42 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += filemanager.h
SOURCES += filemanager.cpp main.cpp
RC_FILE = ico.rc
